fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs-stdlib"
      ref: "4.5.1"
  repositories:
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "db9daeb1831930f648b99e1867867ba6a071e68a"
  symlinks:
    unattended_upgrades: "#{source_dir}"
