fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs-stdlib"
      ref: "4.6.0"
    apt:
      repo: "puppetlabs-apt"
      ref: "2.0.0"
  symlinks:
    unattended_upgrades: "#{source_dir}"
