fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs-stdlib"
      ref: "4.5.1"
  repositories:
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "2.0.x"
  symlinks:
    unattended_upgrades: "#{source_dir}"
